### ISSUE TITLE
UserAgentBlocked/User Agent Restriction (EM new TV Channel)

### ISSUE THREAD

**Issue by galitus** [nirvana-7777/pvr.magenta#7]
Hey,

at first thanks for creating that addon in the first place!

EM is around the corner,  the first new channel (Fussball.TV 1) was already created for the upcoming games which worked flawlessly since, I think tuesday.
But since yesterday or even wednesday the stream seems to be expecting a specific useragent string to stream the content to.

kodi.log (playerid removed because I don't know if that is better not posted) : )
```
debug <general>: AddOnLog: pvr.magenta: function call: [ReleaseLock]
debug <general>: AddOnLog: pvr.magenta: Stream URL -> https://link.api.eu.theplatform.com/s/mdeprod/media/dVgKKSNo1a_e
debug <general>: AddOnLog: pvr.magenta: function call: [GetPersonaToken]
debug <general>: AddOnLog: pvr.magenta: function call: [IsPersonaTokenExpired]

debug <general>: AddOnLog: pvr.magenta: Http-Request: GET https://link.api.eu.theplatform.com/s/mdeprod/media/dVgKKSNo1a_e?format=SMIL&formats=MPEG-DASH&tracking=true&clientId=player_.
debug <general>: CurlFile::Open - <https://link.api.eu.theplatform.com/s/mdeprod/media/dVgKKSNo1a_e?format=SMIL&formats=MPEG-DASH&tracking=true&clientId=player_>

debug <general>: easy_acquire - Created session to https://link.api.eu.theplatform.com
debug <general>: AddOnLog: pvr.magenta: SRC: http://link.theplatform.eu/s/errorFiles/Unavailable.flv
debug <general>: AddOnLog: pvr.magenta: Title: User Agent Restriction
debug <general>: AddOnLog: pvr.magenta: Abstract: This content is not available to this user agent.
debug <general>: AddOnLog: pvr.magenta: Param Name: isException Value: true
debug <general>: AddOnLog: pvr.magenta: Param Name: exception Value: UserAgentBlocked
debug <general>: AddOnLog: pvr.magenta: Param Name: responseCode Value: 403
```

content of dVgKKSNo1a_e:
```
<smil xmlns="http://www.w3.org/2005/SMIL21/Language">
        <head>
        </head>
        <body>
        <seq>
                <ref src="http://link.theplatform.eu/s/errorFiles/Unavailable.flv" title="User Agent Restriction" abstract="This content is not available to this user agent.">
                        <param name="isException" value="true"/>
                        <param name="exception" value="UserAgentBlocked"/>
                        <param name="responseCode" value="403"/>
                        <param name="correlationId" value="631bbe0a-79fc-4931-8888-8d64fc498be2"/>
                </ref>
        </seq>
        </body>
</smil>
```

Maybe you have a way to get the correct user agent added from the android app or stick? : )

self compiled linux amd64 version: 21.9.2 (but the other channels are working, only the guide for the private channels is not loading)
I tried the "magenta stick" and "web device" device type.

Thanks in advance and greetings!

**Comment by nirvana-7777** [comment]
Confirmed that it is not working. However as per my first analysis the error message is misleading. The user agent does not matter. It is about the authorization token. Whatever is in there...

**Comment by nirvana-7777** [comment]
Okay, here is what is happening: The Football Channels do also have a UHD version which is correctly preferred if selected in the seetings. But UHD will only work in original hardware.
I will probably invent UHD blocker or something.

**Comment by galitus** [comment]
Hey, 

thanks for your work. 

Okay, that's why it worked in the beginning. It seems, they activated UHD later. 
I think before it was just FullHD.
If it is an “easy” and intriguing task, your work will be welcomed, but you know the EM is only for a limited time
and we can also use a webplayer, laptop and an HDMI cable as a workaround.
So from my side it is just nice to have.

Thanks again!

**Comment by nirvana-7777** [comment]
Pushed new version 21.9.5 which shall fix the issue by hiding the UHD channels. (As long as they are only working in original HW there is no point in having them...)
